"""create tenants table

Revision ID: c6bfcfcd6ddb
Revises: 
Create Date: 2025-09-15 03:48:00.897631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bfcfcd6ddb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_name', sa.String(), nullable=False),
    sa.Column('tenant_is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_email', sa.String(), nullable=False),
    sa.Column('tenant_phone', sa.String(), nullable=True),
    sa.Column('tenant_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tenant_email'),
    sa.UniqueConstraint('tenant_name'),
    sa.UniqueConstraint('tenant_phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    # ### end Alembic commands ###
