version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass
      POSTGRES_DB: crm_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  crm-core:
    build: .
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload

volumes:
  db_data:
